# Generated by Django 3.2.7 on 2021-11-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('agreement_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('role', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('service_provider_name', models.CharField(max_length=255, unique=True)),
                ('focal_point_name', models.CharField(max_length=255, unique=True)),
                ('focal_point_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiving_UNEP_divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('division_name', models.CharField(max_length=255, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('division_focal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='api.role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('agreement_title', models.CharField(max_length=255, unique=True)),
                ('content_description', models.TextField()),
                ('service_offered', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_name', models.CharField(max_length=255)),
                ('document_attachment', models.FileField(upload_to='documents/')),
                ('agreement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agreement_types')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receiving_unep_divisions')),
                ('focal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service_providers')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='api.profile')),
            ],
        ),
    ]
