# Generated by Django 3.2.7 on 2021-11-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agreements',
            new_name='Agreement',
        ),
        migrations.RenameModel(
            old_name='Agreement_types',
            new_name='Agreement_type',
        ),
        migrations.RenameModel(
            old_name='Receiving_UNEP_divisions',
            new_name='Receiving_UNEP_division',
        ),
        migrations.RenameModel(
            old_name='Service_providers',
            new_name='Service_provider',
        ),
    ]
