# Generated by Django 3.2.7 on 2021-11-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211129_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ('-created_at',)},
        ),
    ]
