# Generated by Django 3.2.7 on 2021-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_digital_assets_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_assets_inventory',
            name='under_development',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
    ]
