# Generated by Django 3.2.7 on 2021-12-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_digital_assets_inventory_under_development'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_assets_inventory',
            name='web_services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
