# Generated by Django 3.2.7 on 2021-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
